on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy Font
      run: |
        mkdir in/ && mkdir out/ && \
        cp ${{ github.repository }}/AtkinsonMonolegible.ttf in/
          

    - name: Run Patcher
      # https://hub.docker.com/r/nerdfonts/patcher
      run: |
        docker run --rm \
          -v /in:/in \
          -v /out:/out \
          nerdfonts/patcher --careful --complete

    - name: Upload output as artifact
      uses: actions/upload-artifact@v3
      with:
        name: font
        path: out
