name: Build & Release

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - run: mkdir out
        
    - name: Patch Font
      run: docker run -v $(pwd):/in:Z -v $(pwd)/out:/out:Z nerdfonts/patcher --complete --careful --no-progressbars
        
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        tag: latest
        name: AtkinsonMonolegibleNerdFont
        omitBody: true
        allowUpdates: true
        removeArtifacts: true
        commit: main
        artifacts: out/*.ttf
