on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - run: mkdir out
        
    - name: Run fontpatcher
      run: docker run -v .:/in:Z -v out:/out:Z nerdfonts/patcher --complete --careful

    - uses: actions/upload-artifact@v3
      with:
        name: nerdfont
        path: out/*
