on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FONT: AtkinsonMonolegible.ttf
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: $FONT
        sparse-checkout-cone-mode: false

    - name: Copy Font
      run: |
        mkdir in/ && mkdir out/ && \
        cp $GITHUB_WORKSPACE/$FONT in/
          

    - name: Run Patcher
      # https://hub.docker.com/r/nerdfonts/patcher
      run: |
        docker run --rm \
          -v /in:/in \
          -v /out:/out \
          nerdfonts/patcher --careful --complete

    - uses: actions/upload-artifact@v3
      with:
        name: nerdfont
        path: out
