on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Copy Font
      run: |
        mkdir in/ \
        && mkdir out/ \
        && cp "$GITHUB_WORKSPACE/AtkinsonMonolegible.ttf" in/ \

    - name: Run Patcher
      uses: addnab/docker-run-action@v3
      with:
        image: nerdfonts/patcher # https://hub.docker.com/r/nerdfonts/patcher
        options: -v /in:/in -v /out:/out
        run: ./nerd/bin/scripts/docker-entrypoint.sh --careful --complete  

    - uses: actions/upload-artifact@v3
      with:
        name: nerdfont
        path: out/*
